;;; consult-dash-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-dash.el

(autoload 'consult-dash "consult-dash" "\
Consult interface for dash documentation.

INITIAL is the default value provided.

(fn &optional INITIAL)" t)
(register-definition-prefixes "consult-dash" '("consult-dash-"))

;;; End of scraped data

(provide 'consult-dash-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-dash-autoloads.el ends here
